### ISSUE TITLE
TERM=xterm-256color for all connection is a slight issue with old Linux versions

### ISSUE THREAD

**Issue by robertstrom** [brightio/penelope#12]
Hello,

I'm working on a very old version of Red Hat (Linux tophat.acme.com 2.4.20-8 \#1 Thu Mar 13 17:54:28 EST 2003 i686 athlon i386 GNU/Linux) and I noticed this when using penelope and trying to clear the screen it would not work and you would get an error about **unknown terminal xterm-256color** 

![image](https://user-images.githubusercontent.com/3240205/185762768-9a553f6a-1a7e-48ed-b354-ca365c02a55f.png)

Trying to clear the terminal

![image](https://user-images.githubusercontent.com/3240205/185762787-59d6668b-39b3-412e-b132-5fa59d5f5cb8.png)

Environment

![image](https://user-images.githubusercontent.com/3240205/185762829-506fa7bd-0edf-456a-ac45-e3e90626ff9d.png)

Setting the TERM variable to **TERM=xterm**
![image](https://user-images.githubusercontent.com/3240205/185762852-078a2e9f-a33b-4275-9dfd-97835e8c1c0d.png)

The clear command works now

![image](https://user-images.githubusercontent.com/3240205/185762867-20df911e-f83f-49c4-b4f1-02722f64dad2.png)

Not a huge deal by any means, not sure if you were aware or had experienced this or not and not sure if you can check for something like this and set the TERM variable to a standard xterm if xterm-256color is not possible.

Thanks for the great tool! I'm loving using it and cannot wait to, hopefully, see some updates in the not too distant future (Windows multiple sessions , etc. ;-) )

**Comment by brightio** [comment]
Hello @robertstrom and thanks again for your kind words :D

Yes I noticed this issue while I was trying to fix the #11 bug you reported on "CentOS release 5.6 (Final)". This is fixed now in version 0.9.0 which is currently in the testing branch and contains several improvements for Linux shells. I will merge it to the main branch later once I fix the Windows shells which are currently a bit broken.

Until then, it would be very helpful if you could use the testing branch (`git switch testing`) and confirm that this issue is fixed, as well as report any other bugs that you may find.

Again, thank you so much for reporting those bugs!
